### ISSUE TITLE
Add syntax highlighting to inline python chunks

### ISSUE THREAD

**Issue by jsdeguzman6** [elderfd/language-weave#2]
I've used the extension recently, and I noticed that in-line python chunks in ;]pweave are highlighted as comments instead of actual chunks, as seen in the image below.
![image](https://user-images.githubusercontent.com/16273400/43671339-a0480e62-97ca-11e8-8cbf-7b0e495c0555.png)
I've seen it implemented in the Atom version of the extension as well, so I was wondering if it could be implemented here as well.

**Comment by elderfd** [comment]
Thanks for the feedback. I've implemented that in a new version of the extension that should be up on the marketplace now.

Let me know if there's any further issues.

**Comment by jsdeguzman6** [comment]
Is it possible to add this for Pweave in LaTeX (.Pnw, .Ptexw) files as well? I forgot to mention I'm using LaTeX for Pweave, my bad.

**Comment by elderfd** [comment]
I haven't used pweave in some time so bear with me. Are you definitely sure the Atom plugin (or even pweave itself) supports inline Python for Latex?

I'm looking at the code for the Atom plugin and it looks like LateX uses the noweb syntax only, which as far as I can tell doesn't have an inline mode.

**Comment by jsdeguzman6** [comment]
Yeah, pweave supports inline Python for LaTeX via noweb syntax via `<%= [one-liner python expression] %>` or `<% [one-liner python expression] %>`. I ran it through Pweave and gave me the expected results. I have yet to check the atom version since I've never really checked atom before.

Edit: Looks like the Atom package doesn't support that either, but it would be nice if it would be supported here as well.

**Comment by elderfd** [comment]
Okay just wanted to double-check I wasn't going to implement highlighting for something that doesn't work with Pweave. Will add that highlighting to LateX too.

**Comment by elderfd** [comment]
Version 0.3.1 has inline highlighting for LateX.
